### ISSUE TITLE
zero_padding

### ISSUE THREAD

**Issue by XXiaoY** [ATP-1010/FederatedLLM#7]
问题1：执行命令：nohup python main.py --global_model './models/TinyLlama-1.1B' --data_path  "./data_wiz" --output_dir './FedIT-zero-wiz-heter/' --num_communication_rounds 2 --local_num_epochs 1 --stacking False --heter True --zero_padding True
出现问题：
Traceback (most recent call last):
  File "/yxh/llm_learner/b_FLoRA/FederatedLLM-main/main.py", line 413, in <module>
    fire.Fire(fl_finetune)
  File "/home/anaconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/anaconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/anaconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/yxh/llm_learner/b_FLoRA/FederatedLLM-main/main.py", line 222, in fl_finetune
    model = get_peft_model(model, config)
UnboundLocalError: local variable 'config' referenced before assignment
![image](https://github.com/user-attachments/assets/d8fb9fa4-d433-4dac-9173-d83847577541)
我的解决方案：将main.py的第222行改成model = get_peft_model(model, config_ori)。

问题2：虽然解决方案修改后能够运行，但是在执行fedavg算法的时候，set_peft_model_state_dict(model, weighted_single_weights, "default")打印输出的model参数并未赋值和修改。
![image](https://github.com/user-attachments/assets/b9bd608a-5d37-4545-8b96-d9c0113fbdae)

问题3：在获取全局聚合模型后，r=max(local_ranks)，那么如何分发给每个r不同的客户端呢？？

**Comment by ziyaow1010** [comment]
你好，已经修改了一下代码逻辑，请尝试一下有无新的报错。
关于问题3，回传r=max(xx)之后client直接用这个r来更新本地模型，然后再重新初始化自己的lora，并不影响整个流程

**Comment by Una0112** [comment]
> 你好，已经修改了一下代码逻辑，请尝试一下有无新的报错。 关于问题3，回传r=max(xx)之后client直接用这个r来更新本地模型，然后再重新初始化自己的lora，并不影响整个流程

if full == False:
            if stacking:
                config_ori.save_pretrained(
                    os.path.join(output_dir, str(epoch)),
                    load_in_8bit=False,
                    torch_dtype=torch.float16,
                    device_map=device_map,
                )
                model = PeftModel.from_pretrained(model, os.path.join(output_dir, str(epoch)))
            else:
                torch.save(model.state_dict(), os.path.join(output_dir, str(epoch), "adapter_model.bin"))
                config.save_pretrained(
                    os.path.join(output_dir, str(epoch)),
                    load_in_8bit=False,
                    torch_dtype=torch.float16,
                    device_map=device_map,
                )
您好，请问zero-padding是否属于这段代码中else以后的情况？如果是的话，那么为什么是config.save_pretrained()而不是config_ori.save_pretrained()？
